language: c
install: sudo apt-get install -y apache2-utils libulfius-dev  libmicrohttpd-dev

jobs:
  include:
  - stage: Build java
    os: linux
    jdk: oraclejdk8
    script:
      - cd java ;  mvn clean package; 
  - stage: Build plain C
    os: linux
    script:
      - cd c && gcc -Wall -Wstrict-prototypes -O2 rest-service.c -o rest-service






